DROP TABLE IF EXISTS ODONTOLOGOS; CREATE TABLE ODONTOLOGOS (ID INT AUTO_INCREMENT PRIMARY KEY, MATRICULA VARCHAR(50) NOT NULL, NOMBRE VARCHAR(100) NOT NULL, APELLIDO VARCHAR(100) NOT NULL);

INSERT INTO ODONTOLOGOS (MATRICULA, NOMBRE, APELLIDO) VALUES (584288,'LEIDY','ALZATE'),(654987,'LADY','SOTO'),(741852,'PABLO','ZAPATA');